name: Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Build and deploy frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Build frontend
        run: |
          cd frontend
          npm run build
          
      - name: Deploy frontend to S3
        run: |
          aws s3 sync frontend/dist s3://${{ secrets.S3_BUCKET }} --delete
          
      - name: Invalidate CloudFront cache
        run: |
          # First get the full bucket domain name from S3
          BUCKET_DOMAIN="${{ secrets.S3_BUCKET }}.s3.amazonaws.com"
          echo "Looking for CloudFront distribution with origin: $BUCKET_DOMAIN"
          
          # Get all distributions and their origins for debugging
          aws cloudfront list-distributions --query "DistributionList.Items[].{Id:Id, Origins:Origins.Items[0].DomainName}" --output json
          
          # Try to find the distribution by origin domain
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Origins.Items[0].DomainName=='$BUCKET_DOMAIN'].Id" --output text)
          
          # If that fails, try a more flexible search
          if [ -z "$DISTRIBUTION_ID" ]; then
            echo "Failed to find exact match. Trying partial match..."
            DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Origins.Items[0].DomainName, '${{ secrets.S3_BUCKET }}')].Id" --output text)
          fi
          
          # Last resort, just take the first distribution (assuming this is a test account with few distributions)
          if [ -z "$DISTRIBUTION_ID" ]; then
            echo "Failed to find by bucket name. Taking first distribution as fallback..."
            DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[0].Id" --output text)
          fi
          
          if [ -n "$DISTRIBUTION_ID" ]; then
            echo "Invalidating CloudFront distribution: $DISTRIBUTION_ID"
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
          else
            echo "Warning: Could not find CloudFront distribution ID. Skipping invalidation."
            # Print all distribution IDs for debugging
            aws cloudfront list-distributions --query "DistributionList.Items[].Id" --output text
          fi

      # Build and deploy backend
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          
      - name: Create deployment package
        run: |
          cd backend
          zip -r ../backend-deploy.zip .
          
      - name: Deploy to Elastic Beanstalk
        run: |
          # First upload the ZIP file to S3
          aws s3 cp backend-deploy.zip s3://${{ secrets.EB_BUCKET }}/backend-deploy-${{ github.sha }}.zip
          
          # Then create the application version referencing that file
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.APP_NAME }} \
            --version-label "ver-${{ github.sha }}" \
            --source-bundle S3Bucket="${{ secrets.EB_BUCKET }}",S3Key="backend-deploy-${{ github.sha }}.zip"
          
          # Finally update the environment to use this version and set environment variables
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.ENV_NAME }} \
            --version-label "ver-${{ github.sha }}" \
            --option-settings \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_NAME,Value=renewable_energy_db_sql \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_HOST,Value=$(aws rds describe-db-instances --query "DBInstances[?DBInstanceIdentifier.contains(@, 'renewable')].Endpoint.Address" --output text) \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_USER,Value=root \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_PASSWORD,Value=${{ secrets.DB_PASSWORD }} \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=ENVIRONMENT,Value=production \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=FRONTEND_URL,Value=https://d2b2j5yt43rmm.cloudfront.net \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=ALLOW_ORIGINS,Value=https://d2b2j5yt43rmm.cloudfront.net